/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordle;

import wordle.data.WordFactory;
import wordle.game.Game;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        String word = WordFactory.createRandomWord();
        System.out.println(word);

        Game wordle = new Game.Builder()
                .setDifficulty(Game.Difficulty.EASY)
                .setWordSize(5)
                .build();


    }
}
