/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordle;

import wordle.data.WordFactory;
import wordle.game.Game;

public class App {
    public static void main(String[] args) {

        Game.Builder wordleBuilder = new Game.Builder()
                .setDifficulty(Game.Difficulty.EASY)
                .setWordSize(5);

        Game wordle = wordleBuilder.build();

        while (wordle.getState() == Game.State.PLAYING) {
            wordle.printBoard();
            String attempt = System.console().readLine();
            wordle.attempt(attempt);
        }
    }
}
